	CREATE TABLE contacto(
		id_pers INT PRIMARY KEY AUTO_INCREMENT,
		full_name VARCHAR(350) NULL DEFAULT NULL,
		email VARCHAR(180) NULL DEFAULT NULL,
		telefono VARCHAR(18) NULL DEFAULT NULL,
		dir_ip VARCHAR(50) NULL DEFAULT NULL,
		token VARCHAR(750) NULL DEFAULT NULL,
		mensaje TEXT NULL DEFAULT NULL,
		created_at DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
		id_created INT NULL DEFAULT 1,
		updated_at DATETIME NULL DEFAULT NULL,
		id_updated INT NULL DEFAULT 0,
		drop_at DATETIME NULL DEFAULT NULL,
		id_drop INT NULL DEFAULT 0,
		status INT(1) NULL DEFAULT 1
	);